# https://github.com/settings/developers
# https://app.netlify.com/projects/silver-trifle-482fa2/configuration/identity#content
backend:
  name: github
  # repo: kubek93/rapoland-events
  branch: main
  # auth_scope: repo

# backend:
#   name: git-gateway
#   branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Start Time", name: "startTime", widget: "string", required: false }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "select", options: ["Technology", "Music", "Art & Culture", "Sports", "Business"] }
      - { label: "Featured Color", name: "color", widget: "select", options: ["blue", "green", "purple", "amber"] }
      - { label: "Attendees", name: "attendees", widget: "list", fields: [{ label: "Name", name: "name", widget: "string" }], required: false }
